### ISSUE TITLE
Inconsistent code style of template literals

### ISSUE THREAD

**Issue by sapegin** [mjavascript/practical-es6#24]
In some places you put spaces inside curly braces:

```js
const message = `The sum of ${ input.join(`+`) } is ${ sum }`
```

but in others you don’t:

```js
const summary = `${units}x ${name} ($${unitPrice}) = $${totalPrice}`
```

**Comment by bevacqua** [comment]
I'm guessing you wouldn't be up to contribute a fix for this? I prefer spaces everywhere 👍

**Comment by sapegin** [comment]
Any ideas how to automate it and won’t make a lot of mistakes? ;-)

**Comment by sapegin** [comment]
Actually you don’t have a lot of them and most already have spaces. I’ll send a PR ;-)

**Comment by bevacqua** [comment]
❤️!
