### ISSUE TITLE
code snippet mismatch

### ISSUE THREAD

**Issue by AmagiDDmxh** [mjavascript/practical-es6#29]
## The code is at the **end of chapter 2.3.4.**
It has a miswrite the '+' identifier in the **sku: brand + ':' [] make**
```
const getCarProductModel = ({ brand, make, model }) => ({
  sku: brand + ':' make + ':' + model,
  brand,
  make,
  model
})
getCarProductModel(car)
```

**Comment by bevacqua** [comment]
Hi. I'm not entirely certain what you mean. Could you ellaborate? Are we talking about the PDF version or the asciidoc source?

**Comment by bevacqua** [comment]
If this is about a rendering issue, this will be fixed in or before copy editing, if not please comment and I'll reopen the issue. Thanks! :tada:
