### ISSUE TITLE
Can't buy book

### ISSUE THREAD

**Issue by likern** [mjavascript/practical-es6#64]
Why I can't buy book? Amazon is the worst choice for ebooks, because there is no way to get and read clean pdf.

1. I use Ubuntu (Linux) and there is no software for ebooks from Amazon
2. No pdf support (for my electronic device PocketBook)
3. Reading online requires exposing a lot of confidential information 
4. Paperback is no choice for faraway countries like Russia (and I want to get updates)

Why shall I grant you:

- Post Tweets for you
- See your email address
- Update your profile
- Read Tweets from your timeline

Don't you think it is too much access rights for you? And violate privacy?
Why do you need such information about people?

It would be good to consider collaborating with other platforms such as Manning publishing (as they provide all formats) or PacktPub Publishing.

I suggest it might be a good book about modern Javascript, but the way how you distribute book gives no change to acquaint with it.

**Comment by likern** [comment]
And O'Really doesn't give ability to buy (excluding Amazon) book directly. Only through https://www.safaribooksonline.com with pricing starting at 400$ per year. Really? That's not a deal.

**Comment by bevacqua** [comment]
Read it in the GitHub repo
