### ISSUE TITLE
ch04: Possible error in output example of "Building Versatility Into Iterating a Playlist"

### ISSUE THREAD

**Issue by vsemozhetbyt** [mjavascript/practical-es6#65]
See last code examples in this [section](https://github.com/mjavascript/practical-modern-javascript/blob/master/ch04.asciidoc#building-versatility-into-iterating-a-playlist).

If I get this right, we get a sequence from the `shuffleSongs()` just once and iterate this sequence every time in the same order. So we cannot have different order inside each loop like:
```
// <- ['a', 'b', 'b', 'a', 'a', 'b']
```
Only these varians are possible:
```
// <- ['a', 'b', 'a', 'b', 'a', 'b']
// <- ['b', 'a', 'b', 'a', 'b', 'a']
```

**Comment by bevacqua** [comment]
This is correct to maintain consistency across runs. If you wanted different orders every time, you can keep calling `playlist()`

**Comment by vsemozhetbyt** [comment]
But in the examples, there are different orders...
