### ISSUE TITLE
Instructions to build epub / pdf /etc

### ISSUE THREAD

**Issue by obaqueiro** [mjavascript/practical-es6#67]
I find that there are no instructions for someone to clone the repository and build an epub, pdf or other book format from the source.  Is that something that is "common knowledge"?  Maybe a small section in the Readme.md would be useful.

**Comment by bevacqua** [comment]
The source is provided as-is. You can read the plain AsciiDoc sources on GitHub, or the rendered HTML on GitHub, or you can read the rendered HTML on Pony Foo, or if you want the PDF/ePub/etc you can buy it on Amazon.

Unfortunately I don't provide support for building the book from sources, but I'd be happy to merge a PR that does it if someone else came up with instructions for it.
