### ISSUE TITLE
I think arrow functions create closures

### ISSUE THREAD

**Issue by jameshbush** [mjavascript/practical-es6#73]
The section Lexical Scoping https://ponyfoo.com/books/practical-modern-javascript/chapters/2#lexical-scoping-8zsxfqh9
claims that arrow functions don't create closures. It looks like they do. In fact, the code relies on closure of arguments in the evaluation of the returned function. I think this should say "arrow functions don't create their own lexical scope, so arguments is accessed from the closure of the enclosing function".

`calc=((a)=>( (b)=>{debugger; return a+b} ))(a=1); calc(2)`

<img width="401" alt="Screen Shot 2019-06-15 at 15 08 04" src="https://user-images.githubusercontent.com/17484767/59555465-9df25100-8f80-11e9-90e5-91ab1cb5d226.png">

**Comment by ljharb** [comment]
They do create their own scope - arrow functions simply don’t create a binding for this/super/arguments, unlike all other functions, so they bubble up lexically.

**Comment by jameshbush** [comment]
Then maybe this:
"In this case, the arguments object refers to the context of the puzzle function, because arrow functions don’t create a closure. For this reason, the printed arguments will be 'a', 'b', 'c'."

Should say this:
"In this case, the arguments object isn't found in local scope, so the variable access bubbles up to the enclosing lexical context of the puzzle function, where arguments is 'a', 'b', 'c'."

(Still learning the terminology. That's the main reason I picked up this book)

**Comment by bevacqua** [comment]
Could you create a PR to fix this? 🙇

**Comment by jameshbush** [comment]
Will do, tomorrow :)

**Comment by jameshbush** [comment]
Opened PR https://github.com/mjavascript/practical-modern-javascript/pull/75

**Comment by bevacqua** [comment]
Fixed in https://github.com/mjavascript/practical-modern-javascript/pull/75
